networks:
  my_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rc-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
    networks:
      - my_network

  db:
    image: postgres:17
    container_name: rc-postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pg_data: